server:
  port: 8777
  servlet:
    session:
      cookie:
        http-only: true # 提升Cookie安全性，防止XSS攻击

spring:
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/
  profiles:
    active: dev


  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: Authorization
    # token临时有效期 [指定时间内无操作就视为token过期] (单位: 秒)
    activity-timeout: 1800
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: false
    is-v: false
    is-read-body: false
    is-read-head: true
#    同一账号多处登录分别生成token 互不影响
    is-share: false

logging:
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: debug

ignored: |
  /v2/*,/favicon.ico,/swagger-resources/**,/druid/**,/swagger-ui.html,/webjars/**,
  /doc.html,/service-worker.js,
  /error,
  /system/file/**,
  /system/user/exportExcel,
  /system/user2/**,
  /active,
  /user-info/login,
  /render,
  /my-user/login